(module
  (import "lifehub_service" "write_response" (func $write (param i32 i32) (result i32)))
  (memory (export "memory") 1)
  (global $counter (mut i32) (i32.const 0))
  (data (i32.const 0) "{\"count\":\"000000\"}")
  (func (export "ready") (result i32) i32.const 1)
  (func (export "tick") (result i32)
    (global.set $counter (i32.add (global.get $counter) (i32.const 1)))
    i32.const 0)
  (func (export "run") (result i32)
    (local $value i32) (local $position i32)
    (local.set $value (global.get $counter))
    (local.set $position (i32.const 15))
    (loop $digit
      (i32.store8 (local.get $position)
        (i32.add (i32.rem_u (local.get $value) (i32.const 10)) (i32.const 48)))
      (local.set $value (i32.div_u (local.get $value) (i32.const 10)))
      (local.set $position (i32.sub (local.get $position) (i32.const 1)))
      (br_if $digit (i32.ge_u (local.get $position) (i32.const 10))))
    (drop (call $write (i32.const 0) (i32.const 18)))
    i32.const 0))
