(module
  (import "lifehub_service" "write_response" (func $reply (param i32 i32) (result i32)))
  (memory (export "memory") 1)
  (global $spent (mut i32) (i32.const 0))
  (data (i32.const 0) "{\"spent\":\"000000\"}")
  (func (export "ready") (result i32) (i32.const 1))
  (func (export "tick") (result i32)
    (global.set $spent (i32.add (global.get $spent) (i32.const 7)))
    (i32.const 0))
  (func (export "run") (result i32)
    (local $rest i32)
    (local $digit i32)
    (local.set $rest (global.get $spent))
    (local.set $digit (i32.const 15))
    (loop $write_digit
      (i32.store8 (local.get $digit)
        (i32.add (i32.const 48)
          (i32.rem_u (local.get $rest) (i32.const 10))))
      (local.set $rest (i32.div_u (local.get $rest) (i32.const 10)))
      (local.set $digit (i32.sub (local.get $digit) (i32.const 1)))
      (br_if $write_digit (i32.ge_s (local.get $digit) (i32.const 10))))
    (drop (call $reply (i32.const 0) (i32.const 18)))
    (i32.const 0)))
